# Set the minimum automatic connection interval to 7.5ms.
# CONFIG_BT_PERIPHERAL_PREF_MIN_INT=6

# The time interval between the secondary hand and the primary hand is 11.25ms.
# CONFIG_BT_PERIPHERAL_PREF_MAX_INT=9

# A latency of 0 means the secondary device will not skip any connection events and will always remain actively listening. This solves the problem of the primary device being unable to wake it up due to deep sleep, although it slightly increases the power consumption of the secondary device.
# CONFIG_BT_PERIPHERAL_PREF_LATENCY=0

# The connection will only be closed if there is no communication within a period of more than 4000ms.
# CONFIG_BT_PERIPHERAL_PREF_TIMEOUT=400

CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_ZMK_BATTERY_REPORT_INTERVAL=60

# Enable 32kHz crystal
CONFIG_CLOCK_CONTROL_NRF_K32SRC_XTAL=y
CONFIG_CLOCK_CONTROL_NRF_K32SRC_30PPM=y

#Turn on knob
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# MOUSE
CONFIG_ZMK_POINTING=y

# CONFIG_ZMK_EXT_POWER=y

# Add keyboard debouncing
# CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=5
# CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=5
# CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y

# Enable keyboard RGB function
# CONFIG_ZMK_RGB_UNDERGLOW=y
# CONFIG_WS2812_STRIP=y
# CONFIG_LED_STRIP=y
# CONFIG_ZMK_RGB_UNDERGLOW_ON_START=y
# CONFIG_ZMK_RGB_UNDERGLOW_EFF_START=3

# CONFIG_ZMK_SLEEP=y
# CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000
# CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y
#This file contains separate configuration files that apply to both sides. The left and right .conf files are for operations when each side has different functional configurations.

# Bluetooth Enhancement
# CONFIG_BT_GATT_ENFORCE_SUBSCRIPTION=y
# CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

#Key remapping
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n
CONFIG_ZMK_STUDIO_LOCK_ON_DISCONNECT=n



